import { Assets, ResolverManifest } from 'pixi.js'

/** List of assets grouped in bundles, for dynamic loading */
let assetsManifest: ResolverManifest = { bundles: [] }

/** Load the assets json manifest generated by assetpack */
async function fetchAssetsManifest(url: string) {
  const response = await fetch(url)
  const manifest = (await response.json()) as ResolverManifest
  if (!manifest.bundles) {
    throw new Error('[Assets] Invalid assets manifest')
  }
  return manifest
}

/** Initialise and start background loading of all assets */
export async function initAssets() {
  // Load assets manifest
  assetsManifest = await fetchAssetsManifest('assets/assets-manifest.json')

  // Init PixiJS assets with this asset manifest
  await Assets.init({ manifest: assetsManifest, basePath: 'assets' })

  await Assets.loadBundle(['common', 'font'])
}
